// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiEwuaSxEFf-gg5HhtuSU_hDk_wgIjIBE',
    appId: '1:168943977278:web:c90e117624ba332edea26f',
    messagingSenderId: '168943977278',
    projectId: 'datn-cdbee',
    authDomain: 'datn-cdbee.firebaseapp.com',
    storageBucket: 'datn-cdbee.appspot.com',
    measurementId: 'G-ZGTTPB1GPC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVWyEyNUKNgTu3M5db1RFLuFpY2kBFToE',
    appId: '1:168943977278:android:2e6d6842f591895fdea26f',
    messagingSenderId: '168943977278',
    projectId: 'datn-cdbee',
    storageBucket: 'datn-cdbee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8jQg6uenUBWI2devQ7Lf7Vo-qaz8zCY8',
    appId: '1:168943977278:ios:2609f0abc5aedd6fdea26f',
    messagingSenderId: '168943977278',
    projectId: 'datn-cdbee',
    storageBucket: 'datn-cdbee.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8jQg6uenUBWI2devQ7Lf7Vo-qaz8zCY8',
    appId: '1:168943977278:ios:705c8460d83e303fdea26f',
    messagingSenderId: '168943977278',
    projectId: 'datn-cdbee',
    storageBucket: 'datn-cdbee.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
